name: OnePlus Kernel Build

on:
  workflow_dispatch:
    inputs:
      oplus_branch:
        type: choice
        required: true
        options:
          - oneplus/sm8750
          - oneplus/sm8650
          - oneplus/sm8550
          - oneplus/sm8475
          - oneplus/sm7675
          - oneplus/sm7550
          - other
        description: OnePlus source code branch
      oplus_other_branch:
        type: string
        required: false
        description: OnePlus source code other branch
      oplus_name:
        type: choice
        required: true
        options:
          - oneplus_13r
          - oneplus12_u
          - oneplus12_v
          - oneplus_12r_v
          - oneplus_11_v
          - oneplus_11r_v
          - oneplus_ace5
          - oneplus_ace3_v
          - oneplus_ace3_pro
          - oneplus_ace3_pro_v
          - oneplus_ace2_v
          - oneplus_ace2pro_v
          - other
        description: OnePlus phone model
      oplus_other_name:
        type: string
        required: false
        description: OnePlus ohter phone model
      susfs_branch:
        type: choice
        required: true
        options:
          - gki-android15-6.6
          - gki-android14-6.1
          - gki-android14-5.15
          - gki-android13-5.15
          - gki-android13-5.10
          - gki-android12-5.10
          - other
        description: susfs4ksu branch
      susfs_other_branch:
        type: string
        required: false
        description: susfs4ksu other branch
      kernel_name_suffix:
        type: string
        required: false
        default: "sukev"
        description: Kernel name suffix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          
      - name: Initialize environment
        run: |
          # oplus branch
          if [ "${{ inputs.oplus_branch }}" = "other" ]; then
            echo "OPLUS_BRANCH=${{ inputs.oplus_other_branch }}" >> $GITHUB_ENV
          else
            echo "OPLUS_BRANCH=${{ inputs.oplus_branch }}" >> $GITHUB_ENV
          fi
          # oplus name
          if [ "${{ inputs.oplus_name }}" = "other" ]; then
            echo "OPLUS_NAME=${{ inputs.oplus_other_name }}" >> $GITHUB_ENV
          else
            echo "OPLUS_NAME=${{ inputs.oplus_name }}" >> $GITHUB_ENV
          fi
          # susfs4ksu branch
          if [ "${{ inputs.susfs_branch }}" = "other" ]; then
            echo "SUSFS_BRANCH=${{ inputs.susfs_other_branch }}" >> $GITHUB_ENV
          else
            echo "SUSFS_BRANCH=${{ inputs.susfs_branch }}" >> $GITHUB_ENV
          fi
          # kernel name suffix
          if [ -z "${{ inputs.kernel_name_suffix}}" ]; then
            echo "KERNEL_NAME_SUFFIX=" >> $GITHUB_ENV
          else
            echo "KERNEL_NAME_SUFFIX=-${{ inputs.kernel_name_suffix }}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 python-is-python3
          curl -LO https://storage.googleapis.com/git-repo-downloads/repo
          sudo install -m 0755 repo /usr/local/bin && rm -f repo
      
      - name: Initialize and sync kernel source
        run: |
          # susfs4ksu
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b ${{ env.SUSFS_BRANCH }} --depth 1

          # OnePlus kernel
          mkdir -p oplus && cd oplus
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b ${{ env.OPLUS_BRANCH }} -m ${{ env.OPLUS_NAME }}.xml --depth 1
          repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

          # KernelSU-Next
          cd kernel_platform/common
          curl -LSs https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next-susfs/kernel/setup.sh | bash -s next-susfs

      - name: Apply susfs patches
        run: |
          cd oplus/kernel_platform
          cp ../../susfs4ksu/kernel_patches/50_add_susfs_in_${{ env.SUSFS_BRANCH }}.patch ./common/
          cp ../../susfs4ksu/kernel_patches/fs/* ./common/fs/
          cp ../../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/

          cd common
          patch -p1 < 50_add_susfs_in_${{ env.SUSFS_BRANCH }}.patch

      - name: Replace the kernel name
        run: |
          cd oplus/kernel_platform
          sed -i '$s|echo "\$res"|echo "\$res${{ env.KERNEL_NAME_SUFFIX }}"|' ./common/scripts/setlocalversion
          sed -i '$s|echo "\$res"|echo "\$res${{ env.KERNEL_NAME_SUFFIX }}"|' ./msm-kernel/scripts/setlocalversion
          sed -i 's/-dirty//' ./common/scripts/setlocalversion
          sed -i 's/-dirty//' ./msm-kernel/scripts/setlocalversion

      - name: Build the kernel
        run: |
          cd oplus
          rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
          sed -i '/echo "LTO $LTO "/i export LTO=thin' ./kernel_platform/oplus/build/oplus_setup.sh
          ./kernel_platform/oplus/build/oplus_build_kernel.sh default gki
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: boot-artifact
          path: |
            oplus/out/dist/boot.img

      - name: Cleanup workspace
        run: |
          rm -rf $GITHUB_WORKSPACE/*
